### PR TITLE
Armed to the teeth -> Anthem of Battle

### PR DESCRIPTION
**Pull request by chisquare130**
Replaced all occurrences of "Armed to the Teeth" with "Anthem of Battle"

### CODE REVIEW

**Comment by cbeck88** [comment]
I think you don't actually want to remove this line:

https://github.com/davewx7/citadel/pull/29/files#diff-949426329d059831b1331f66e690c30aL681

The problem is that many people have "Armed to the Teeth" in their decks. If the card "Armed to the Teeth" is wholly deleted from the cards database, then when they try to play their game will crash. For now we use this alias system so that old names still link to the new names. That's the purpose of the line "Armed to the Teeth" : "Anthem of Battle".

We could try to make it so that when the game loads a user's deck and sees that it is following links, it updates the names permanently. But even then you will still have to leave the link in for a while I guess.

Until the system gets changed though that line probably needs to stay in.

**Comment by chisquare130** [comment]
Can you tell me how to merge commits, please?

**Comment by cbeck88** [comment]
So, the simplest way to edit commits is to use "git commit --amend", which allows you to modify the most recent commit.

If you have to modify commits from earlier than that, the best way is to use "git rebase" in interactive mode. You type "git rebase -i HEAD^^^" or similar, and in the text editor that opens up, you change some of the commits marked "pick" to "squash" or "fixup", which will squash them in with the commit before them. Squash combines their commit messages, and fixup discards the later commit message.

After that, you push your branch with force, to your repository, and your pull request will be updated. You have to push with force because when you rebase or use commit --amend, you are altering the history.

**Comment by chisquare130** [comment]
Thanks, I think I've finally figured out how to do it. Keeps an alias and replaces all other occurrences.

**Comment by cbeck88** [comment]
@davewx7 , @Velensk , one of you guys needs to take a look at this, I'm not actually going to merge it, I was just pointing out of a problem.

**Comment by chisquare130** [comment]
Close as it is already merged

**Pull request closed without merging**
