### PR TITLE
'Missionaria Protectiva' implementation

### PR DESCRIPTION
**Pull request by pacnutek**
'Missionaria Protectiva' implementation and enhancement of the Bamboo Forest

### CODE REVIEW

**Comment by galegosimpatico** [comment]
GitHub isn't able to handle that as gracefully as Git, so I'm going to perform a classic merge.

**Comment by pacnutek** [comment]
Hi. Thanks for the merge and comment. I was wondering myself why there where those other revisions attached. I pulled them from upstream 2 minutes before the pull request (did a rebase after that).
I thought I finally got git but nope, it still eludes me.

**Comment by galegosimpatico** [comment]
> Hi. Thanks for the merge and comment. I was wondering myself why there where those other revisions attached. I pulled them from upstream 2 minutes before the pull request (did a rebase after that).
I thought I finally got git but nope, it still eludes me.

Which was the application with which you did the rebase?

**Comment by pacnutek** [comment]
Git, the bash console under windows.

**Pull request merged**
