### PR TITLE
"Sleep" spell (maybe mergable now :) )

### PR DESCRIPTION
**Pull request by cbeck88**

### CODE REVIEW

**Comment by Andrettin** [comment]
I like this idea - and it, along with the Pyre Zombie card, would make a nice addition to the opponent's deck in certain scenarios of The First Dwarves. What is still buggy with the card/effect?

**Comment by cbeck88** [comment]
The first bug was that the sleep wore off before the period in which they were supposed to be sleeping. Then the bug was that it never wore off. Now it seems to be just right -- assuming Dave doesn't think I butchered the code organization :)

**Comment by davewx7** [comment]
Can you simplify the code by just making it so instead of wearing sleep off
at the end of the controller's turn make it wear it off at the *beginning*
of the enemy's turn? I think that would work wouldn't it?

**Comment by cbeck88** [comment]
That's what it currently does. I think rather than checking "current controller != creature owner" though, its better to have a flag that checks "did a turn of mine pass during which I was sleeping", because then I guess it would work correctly if you generalize to having 3 players in a game or something.

**Comment by davewx7** [comment]
Okay, sounds good! Go ahead and commit it! :)

**Pull request merged**
